# Generated by Django 3.1.6 on 2021-02-05 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade_total', models.IntegerField(blank=True, default=0, null=True)),
                ('quantidade_emitida', models.IntegerField(blank=True, default=0, null=True)),
                ('quantidade_recebida', models.IntegerField(blank=True, default=0, null=True)),
                ('preco_unitario', models.IntegerField(blank=True, default=0, null=True)),
                ('nome_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('quandidade_recebida', models.IntegerField(blank=True, default=0, null=True)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('preco_unitario', models.IntegerField(blank=True, default=0, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
    ]
